CREATE DATABASE QLBVMB
GO
USE QLBVMB
GO

CREATE TABLE MAYBAY(
    MaMayBay VARCHAR(10) PRIMARY KEY,
    TenSanBay NVARCHAR(50) NOT NULL
)

create table KHACHHANG(
    CMND VARCHAR(15) PRIMARY KEY,
    TenKH NVARCHAR(50) NOT NULL,
    SDT VARCHAR(15),
    GioiTinh NVARCHAR(5)
)

create table VE(
    MaVe VARCHAR(10) PRIMARY KEY,
    GiaVe FLOAT NOT NULL,
    GheNgoi VARCHAR(10) UNIQUE NOT NULL,
    MaMayBay VARCHAR(10) NOT NULL,
    KhungGioBay TIME NOT NULL
    FOREIGN KEY(MaMayBay) REFERENCES MAYBAY(MaMayBay)
)
create table HOADON(
    MaHoaDon VARCHAR(10) PRIMARY KEY,
    CMND VARCHAR(15) REFERENCES KHACHHANG(CMND),
    MaVe VARCHAR(10) REFERENCES VE(MaVe),
    NgayLap DATE NOT NULL,
    ThanhTien FLOAT NOT NULL
)


